# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 15:16
from __future__ import unicode_literals

import apps.core.models
import datetime
from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=50, verbose_name='Primeiro nome')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='username')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('is_member', models.BooleanField(default=True, verbose_name='Membro?')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Administrador?')),
                ('created_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Criado em')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.core.models.update_filename, verbose_name='Foto')),
                ('photo_thumb', image_cropping.fields.ImageRatioField('photo', '110x110', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='photo thumb')),
            ],
            options={
                'verbose_name': 'Usu\xe1rio',
                'verbose_name_plural': 'Usu\xe1rios',
            },
        ),
    ]
