# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descri\xe7\xe3o'),
        ),
    ]
