# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 19:18
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20160411_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='post',
            name='method_of_preparation',
        ),
        migrations.RemoveField(
            model_name='post',
            name='produce',
        ),
        migrations.RemoveField(
            model_name='post',
            name='time_of_preparation',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Conte\xfado'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='T\xedtulo'),
        ),
    ]
